name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Cat Facts.json" -e "37582007-5e3ddad0-4ef7-4398-8cf7-d3a509709a42" --integration-id "179263-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint d99ca0f8-82de-4a2a-970c-b3c2aa1d9417 --integration-id 179263
